// Yo'l belgilari ma'lumotlari.
// Har bir guruhga belgilar "signs" ro'yxatiga qo'shiladi.
// Misol: { img: "images/ogohlantiruvchi/1.jpg", name: "Temir yo'l kechuvi" }

const signsData = {
    1: {
        title: "1. Ogohlantiruvchi belgilar",
        signs: [
            { num: "1.1",    img: "images/ogohlantiruvchi/1.1.png",    name: "Shlagbaumli temir yo'l kesishmasi" },
            { num: "1.2",    img: "images/ogohlantiruvchi/1.2.png",    name: "Shlagbaumsiz temir yo'l kesishmasi" },
            { num: "1.3",    img: "images/ogohlantiruvchi/1.3.png",    name: "Diqqat \"UZP\"" },
            { num: "1.3.1",  img: "images/ogohlantiruvchi/1.3.1.png",  name: "Bir izli temir yo'l" },
            { num: "1.3.2",  img: "images/ogohlantiruvchi/1.3.2.png",  name: "Ko'p izli temir yo'l" },
            { num: "1.4.1",  img: "images/ogohlantiruvchi/1.4.1.png",  name: "Temir yo'l kesishmasining oldingi belgisi" },
            { num: "1.4.2",  img: "images/ogohlantiruvchi/1.4.2.png",  name: "Temir yo'l kesishmasining oldingi belgisi" },
            { num: "1.4.3",  img: "images/ogohlantiruvchi/1.4.3.png",  name: "Temir yo'l kesishmasining oldingi belgisi" },
            { num: "1.4.4",  img: "images/ogohlantiruvchi/1.4.4.png",  name: "Temir yo'l kesishmasining oldingi belgisi" },
            { num: "1.4.5",  img: "images/ogohlantiruvchi/1.4.5.png",  name: "Temir yo'l kesishmasining oldingi belgisi" },
            { num: "1.4.6",  img: "images/ogohlantiruvchi/1.4.6.png",  name: "Temir yo'l kesishmasining oldingi belgisi" },
            { num: "1.5",    img: "images/ogohlantiruvchi/1.5.png",    name: "Tramvay yo'li bilan kesishuv" },
            { num: "1.6",    img: "images/ogohlantiruvchi/1.6.png",    name: "Teng ahamiyatli yo'llar kesishuvi" },
            { num: "1.7",    img: "images/ogohlantiruvchi/1.7.png",    name: "Aylanma harakatlanish bilan kesishuv" },
            { num: "1.8",    img: "images/ogohlantiruvchi/1.8.png",    name: "Svetofor tartibga soladi" },
            { num: "1.9",    img: "images/ogohlantiruvchi/1.9.png",    name: "Ko'tarma ko'prik" },
            { num: "1.10",   img: "images/ogohlantiruvchi/1.10.png",   name: "Sohilga chiqish" },
            { num: "1.11.1", img: "images/ogohlantiruvchi/1.11.1.png", name: "Xavfli burilish" },
            { num: "1.11.2", img: "images/ogohlantiruvchi/1.11.2.png", name: "Xavfli burilish" },
            { num: "1.12.1", img: "images/ogohlantiruvchi/1.12.1.png", name: "Xavfli burilishlar" },
            { num: "1.12.2", img: "images/ogohlantiruvchi/1.12.2.png", name: "Xavfli burilishlar" },
            { num: "1.13",   img: "images/ogohlantiruvchi/1.13.png",   name: "Tik nishablik" },
            { num: "1.14",   img: "images/ogohlantiruvchi/1.14.png",   name: "Tik balandlik" },
            { num: "1.15",   img: "images/ogohlantiruvchi/1.15.png",   name: "Sirpanchiq yo'l" },
            { num: "1.16",   img: "images/ogohlantiruvchi/1.16.png",   name: "Notekis yo'l" },
            { num: "1.17",   img: "images/ogohlantiruvchi/1.17.png",   name: "Tosh otilish xavfi" },
            { num: "1.18.1", img: "images/ogohlantiruvchi/1.18.1.png", name: "Yo'lning torayishi" },
            { num: "1.18.2", img: "images/ogohlantiruvchi/1.18.2.png", name: "Yo'lning torayishi" },
            { num: "1.18.3", img: "images/ogohlantiruvchi/1.18.3.png", name: "Yo'lning torayishi" },
            { num: "1.19",   img: "images/ogohlantiruvchi/1.19.png",   name: "Ikki tomonlama harakatlanish" },
            { num: "1.20",   img: "images/ogohlantiruvchi/1.20.png",   name: "Piyodalar o'tish joyi" },
            { num: "1.21",   img: "images/ogohlantiruvchi/1.21.png",   name: "Bolalar" },
            { num: "1.22",   img: "images/ogohlantiruvchi/1.22.png",   name: "Velosiped yo'lkasi bilan kesishuv" },
            { num: "1.23",   img: "images/ogohlantiruvchi/1.23.png",   name: "Ta'mirlash ishlari" },
            { num: "1.24",   img: "images/ogohlantiruvchi/1.24.png",   name: "Mol haydab o'tish" },
            { num: "1.25",   img: "images/ogohlantiruvchi/1.25.png",   name: "Yovvoyi hayvonlar" },
            { num: "1.26",   img: "images/ogohlantiruvchi/1.26.png",   name: "Toshlar tushishi" },
            { num: "1.27",   img: "images/ogohlantiruvchi/1.27.png",   name: "Yonlama shamol" },
            { num: "1.28",   img: "images/ogohlantiruvchi/1.28.png",   name: "Pastlab uchuvchi samolyotlar" },
            { num: "1.29",   img: "images/ogohlantiruvchi/1.29.png",   name: "Tonnel" },
            { num: "1.30",   img: "images/ogohlantiruvchi/1.30.png",   name: "Boshqa xavf-xatar" },
            { num: "1.31",   img: "images/ogohlantiruvchi/1.31.png",   name: "Sun'iy yo'l notekisliklari" },
            { num: "1.31.1", img: "images/ogohlantiruvchi/1.31.1.png", name: "Burilishning yo'nalishi" },
            { num: "1.31.2", img: "images/ogohlantiruvchi/1.31.2.png", name: "Burilishning yo'nalishi" },
            { num: "1.31.3", img: "images/ogohlantiruvchi/1.31.3.png", name: "Burilishning yo'nalishi" },
            { num: "1.32",   img: "images/ogohlantiruvchi/1.32.png",   name: "Tirbandlik" }
        ]
    },
    2: {
        title: "2. Imtiyozli belgilari",
        signs: [
            { num: "2.1",   img: "images/imtiyoz/2.1.png",   name: "Asosiy yo'l" },
            { num: "2.2",   img: "images/imtiyoz/2.2.png",   name: "Asosiy yo'lning oxiri" },
            { num: "2.3.1", img: "images/imtiyoz/2.3.1.png", name: "Ikkinchi darajali yo'l bilan kesishuv" },
            { num: "2.3.2", img: "images/imtiyoz/2.3.2.png", name: "Ikkinchi darajali yo'lning o'ngdan tutashuvi" },
            { num: "2.3.3", img: "images/imtiyoz/2.3.3.png", name: "Ikkinchi darajali yo'lning chapdan tutashuvi" },
            { num: "2.4",   img: "images/imtiyoz/2.4.png",   name: "Yo'l bering" },
            { num: "2.5",   img: "images/imtiyoz/2.5.png",   name: "To'xtamasdan harakatlanish taqiqlangan" },
            { num: "2.6",   img: "images/imtiyoz/2.6.png",   name: "Qarama-qarshi harakatlanishning ustunligi" },
            { num: "2.7",   img: "images/imtiyoz/2.7.png",   name: "Qarama-qarshi harakatlanishga nisbatan ustunlik" }
        ]
    },
    3: {
        title: "3. Ta'qiqlovchi belgilar",
        signs: [
            { num: "3.1",    img: "images/taqiqlovchi/3.1.png",    name: "Kirish ta'qiqlangan" },
            { num: "3.2",    img: "images/taqiqlovchi/3.2.png",    name: "Harakatlanish ta'qiqlangan" },
            { num: "3.3",    img: "images/taqiqlovchi/3.3.png",    name: "Mexanik transport vositalarining harakatlanishi ta'qiqlangan" },
            { num: "3.4",    img: "images/taqiqlovchi/3.4.png",    name: "Yuk avtomobillarining harakatlanishi ta'qiqlangan" },
            { num: "3.5",    img: "images/taqiqlovchi/3.5.png",    name: "Mototsikllar harakatlanishi ta'qiqlangan" },
            { num: "3.6",    img: "images/taqiqlovchi/3.6.png",    name: "Traktorlar harakatlanishi ta'qiqlangan" },
            { num: "3.7",    img: "images/taqiqlovchi/3.7.png",    name: "Tirkama bilan harakatlanish ta'qiqlangan" },
            { num: "3.8",    img: "images/taqiqlovchi/3.8.png",    name: "Ot-arava harakatlanishi ta'qiqlangan" },
            { num: "3.9",    img: "images/taqiqlovchi/3.9.png",    name: "Velosipedda harakatlanish ta'qiqlangan" },
            { num: "3.10",   img: "images/taqiqlovchi/3.10.png",   name: "Piyodalarning harakatlanishi ta'qiqlangan" },
            { num: "3.11",   img: "images/taqiqlovchi/3.11.png",   name: "Vazn cheklangan" },
            { num: "3.12",   img: "images/taqiqlovchi/3.12.png",   name: "O'qqa tushadigan og'irlik cheklangan" },
            { num: "3.13",   img: "images/taqiqlovchi/3.13.png",   name: "Cheklangan balandlik" },
            { num: "3.14",   img: "images/taqiqlovchi/3.14.png",   name: "Cheklangan kenglik" },
            { num: "3.15",   img: "images/taqiqlovchi/3.15.png",   name: "Cheklangan uzunlik" },
            { num: "3.16",   img: "images/taqiqlovchi/3.16.png",   name: "Eng kam oraliq" },
            { num: "3.17.1", img: "images/taqiqlovchi/3.17.1.png", name: "Bojxona" },
            { num: "3.17.2", img: "images/taqiqlovchi/3.17.2.png", name: "Xavf-xatar" },
            { num: "3.18.1", img: "images/taqiqlovchi/3.18.1.png", name: "O'ngga burilish ta'qiqlanadi" },
            { num: "3.18.2", img: "images/taqiqlovchi/3.18.2.png", name: "Chapga burilish ta'qiqlanadi" },
            { num: "3.19",   img: "images/taqiqlovchi/3.19.png",   name: "Qayrilish ta'qiqlanadi" },
            { num: "3.20",   img: "images/taqiqlovchi/3.20.png",   name: "Quvib o'tish ta'qiqlanadi" },
            { num: "3.21",   img: "images/taqiqlovchi/3.21.png",   name: "Quvib o'tish ta'qiqlangani tugashi" },
            { num: "3.22",   img: "images/taqiqlovchi/3.22.png",   name: "Yuk avtomobillarida quvib o'tish ta'qiqlanadi" },
            { num: "3.23",   img: "images/taqiqlovchi/3.23.png",   name: "Yuk avtomobillarida quvib o'tish ta'qiqlangani tugashi" },
            { num: "3.24",   img: "images/taqiqlovchi/3.24.png",   name: "Yuqori tezlik cheklangan" },
            { num: "3.25",   img: "images/taqiqlovchi/3.25.png",   name: "Yuqori tezlik cheklangan hududning tugashi" },
            { num: "3.26",   img: "images/taqiqlovchi/3.26.png",   name: "Tovush moslamalaridan foydalanish ta'qiqlanadi" },
            { num: "3.27",   img: "images/taqiqlovchi/3.27.png",   name: "To'xtash ta'qiqlangan" },
            { num: "3.28",   img: "images/taqiqlovchi/3.28.png",   name: "To'xtab turish ta'qiqlangan" },
            { num: "3.29",   img: "images/taqiqlovchi/3.29.png",   name: "Oyning toq kunlarida to'xtab turish ta'qiqlangan" },
            { num: "3.30",   img: "images/taqiqlovchi/3.30.png",   name: "Oyning juft kunlarida to'xtab turish ta'qiqlangan" },
            { num: "3.31",   img: "images/taqiqlovchi/3.31.png",   name: "Barcha cheklovlarning oxiri" },
            { num: "3.32",   img: "images/taqiqlovchi/3.32.png",   name: "Xavfli yuklarga ega transport vositalarining harakatlanishi ta'qiqlangan" },
            { num: "3.33",   img: "images/taqiqlovchi/3.33.png",   name: "Portlovchi va yonuvchan yuklarga ega transport vositalarining harakatlanishi ta'qiqlangan" }
        ]
    },
    4: {
        title: "4. Buyuruvchi belgilar",
        signs: [
            { num: "4.1.1", img: "images/buyuruvchi/4.1.1.png", name: "Harakatlanish to'g'riga" },
            { num: "4.1.2", img: "images/buyuruvchi/4.1.2.png", name: "Harakatlanish o'ngga" },
            { num: "4.1.3", img: "images/buyuruvchi/4.1.3.png", name: "Harakatlanish chapga" },
            { num: "4.1.4", img: "images/buyuruvchi/4.1.4.png", name: "Harakatlanish to'g'riga yoki o'ngga" },
            { num: "4.1.5", img: "images/buyuruvchi/4.1.5.png", name: "Harakatlanish to'g'riga yoki chapga" },
            { num: "4.1.6", img: "images/buyuruvchi/4.1.6.png", name: "Harakatlanish o'ngga yoki chapga" },
            { num: "4.2.1", img: "images/buyuruvchi/4.2.1.png", name: "To'siqni o'ngdan chetlab o'tish" },
            { num: "4.2.2", img: "images/buyuruvchi/4.2.2.png", name: "To'siqni chapdan chetlab o'tish" },
            { num: "4.2.3", img: "images/buyuruvchi/4.2.3.png", name: "To'siqni o'ngdan yoki chapdan chetlab o'tish" },
            { num: "4.3",   img: "images/buyuruvchi/4.3.png",   name: "Aylanma harakatlanish" },
            { num: "4.4",   img: "images/buyuruvchi/4.4.png",   name: "Yengil avtomobillar harakatlanadi" },
            { num: "4.5",   img: "images/buyuruvchi/4.5.png",   name: "Velosiped yo'lkasi" },
            { num: "4.6",   img: "images/buyuruvchi/4.6.png",   name: "Piyodalar yo'lkasi" },
            { num: "4.6.1", img: "images/buyuruvchi/4.6.1.png", name: "Piyoda va velosipedlar birgalikda harakatlanish yo'li" },
            { num: "4.6.2", img: "images/buyuruvchi/4.6.2.png", name: "Piyoda va velosipedlar birgalikda harakatlanish yo'li oxiri" },
            { num: "4.6.3", img: "images/buyuruvchi/4.6.3.png", name: "Ajratilgan piyoda va velosiped harakatlanish yo'li" },
            { num: "4.6.4", img: "images/buyuruvchi/4.6.4.png", name: "Ajratilgan piyoda va velosiped harakatlanish yo'li oxiri" },
            { num: "4.6.5", img: "images/buyuruvchi/4.6.5.png", name: "Ajratilgan piyoda va velosiped harakatlanish yo'li" },
            { num: "4.6.6", img: "images/buyuruvchi/4.6.6.png", name: "Ajratilgan piyoda va velosiped harakatlanish yo'li oxiri" },
            { num: "4.7",   img: "images/buyuruvchi/4.7.png",   name: "Eng kam tezlik" },
            { num: "4.8",   img: "images/buyuruvchi/4.8.png",   name: "Eng kam tezlik belgilangan yo'lning oxiri" },
            { num: "4.9.1", img: "images/buyuruvchi/4.9.1.png", name: "Transport vositalarining xavfli yuklar bilan harakatlanish yo'nalishi" },
            { num: "4.9.2", img: "images/buyuruvchi/4.9.2.png", name: "Transport vositalarining xavfli yuklar bilan harakatlanish yo'nalishi" },
            { num: "4.9.3", img: "images/buyuruvchi/4.9.3.png", name: "Transport vositalarining xavfli yuklar bilan harakatlanish yo'nalishi" },
            { num: "4.10",  img: "images/buyuruvchi/4.10.png",  name: "Otda yurish yo'li" }
        ]
    },
    5: {
        title: "5. Axborot-ishora belgilari",
        signs: [
            { num: "5.1", img: "images/axborot-ishora/5.1.png", name: "Avtomagistral" },
            { num: "5.2", img: "images/axborot-ishora/5.2.png", name: "Avtomagistralning oxiri" },
            { num: "5.3", img: "images/axborot-ishora/5.3.png", name: "Avtomobillar uchun mo'ljallangan yo'l" },
            { num: "5.4", img: "images/axborot-ishora/5.4.png", name: "Avtomobillar uchun mo'ljallangan yo'lning oxiri" },
            { num: "5.5", img: "images/axborot-ishora/5.5.png", name: "Bir tomonlama harakatlanish yo'li" },
            { num: "5.6", img: "images/axborot-ishora/5.6.png", name: "Bir tomonlama harakatlanish yo'lining oxiri" },
            { num: "5.7.1", img: "images/axborot-ishora/5.7.1.png", name: "Bir tomonlama harakatlanish yo'liga chiqish" },
            { num: "5.7.2", img: "images/axborot-ishora/5.7.2.png", name: "Bir tomonlama harakatlanish yo'liga chiqish" },
            { num: "5.8.1", img: "images/axborot-ishora/5.8.1.png", name: "Bo'laklar bo'yicha harakatlanish yo'nalishi" },
            { num: "5.8.2", img: "images/axborot-ishora/5.8.2a.png", name: "Bo'lak bo'yicha harakatlanish yo'nalishi" },
            { num: "5.8.2", img: "images/axborot-ishora/5.8.2b.png", name: "Bo'lak bo'yicha harakatlanish yo'nalishi" },
            { num: "5.8.2", img: "images/axborot-ishora/5.8.2c.png", name: "Bo'lak bo'yicha harakatlanish yo'nalishi" },
            { num: "5.8.2", img: "images/axborot-ishora/5.8.2d.png", name: "Bo'lak bo'yicha harakatlanish yo'nalishi" },
            { num: "5.8.3", img: "images/axborot-ishora/5.8.3a.png", name: "Bo'lakning boshlanishi" },
            { num: "5.8.3", img: "images/axborot-ishora/5.8.3b.png", name: "Bo'lakning boshlanishi" },
            { num: "5.8.4", img: "images/axborot-ishora/5.8.4.png", name: "Bo'lakning boshlanishi" },
            { num: "5.8.5", img: "images/axborot-ishora/5.8.5a.png", name: "Bo'lak oxiri" },
            { num: "5.8.5", img: "images/axborot-ishora/5.8.5b.png", name: "Bo'lak oxiri" },
            { num: "5.8.7", img: "images/axborot-ishora/5.8.7a.png", name: "Bo'laklar bo'yicha harakatlanish yo'nalishi" },
            { num: "5.8.7", img: "images/axborot-ishora/5.8.7b.png", name: "Bo'laklar bo'yicha harakatlanish yo'nalishi" },
            { num: "5.8.8", img: "images/axborot-ishora/5.8.8.png", name: "Bo'laklar bo'yicha harakatlanish yo'nalishi" },
            { num: "5.8.9", img: "images/axborot-ishora/5.8.9.png", name: "Bo'laklar soni" },
            { num: "5.9", img: "images/axborot-ishora/5.9.png", name: "Belgilangan yo'nalishli transport vositalari yo'lagi" },
            { num: "5.10.1", img: "images/axborot-ishora/5.10.1.png", name: "Belgilangan yo'nalishli transport vositalari yo'lagi bo'lgan yo'l" },
            { num: "5.10.2", img: "images/axborot-ishora/5.10.2.png", name: "Belgilangan yo'nalishli transport vositalari yo'lagi bo'lgan yo'l" },
            { num: "5.10.3", img: "images/axborot-ishora/5.10.3.png", name: "Belgilangan yo'nalishli transport vositalari yo'lagidan chiqish" },
            { num: "5.10.4", img: "images/axborot-ishora/5.10.4.png", name: "Belgilangan yo'nalishli transport vositalari yo'lagidan chiqish" },
            { num: "5.11.1", img: "images/axborot-ishora/5.11.1.png", name: "Qayirilish joyi" },
            { num: "5.11.2", img: "images/axborot-ishora/5.11.2.png", name: "Qayirilish oralig'i" },
            { num: "5.12", img: "images/axborot-ishora/5.12.png", name: "Avtobus va trolleybus to'xtash joyi" },
            { num: "5.13", img: "images/axborot-ishora/5.13.png", name: "Tramvay to'xtash joyi" },
            { num: "5.14", img: "images/axborot-ishora/5.14.png", name: "Taksi to'xtab turish joyi" },
            { num: "5.15", img: "images/axborot-ishora/5.15.png", name: "To'xtab turish joyi" },
            { num: "5.16.1", img: "images/axborot-ishora/5.16.1.png", name: "Piyodalar o'tish joyi" },
            { num: "5.16.2", img: "images/axborot-ishora/5.16.2.png", name: "Piyodalar o'tish joyi" },
            { num: "5.17.1", img: "images/axborot-ishora/5.17.1.png", name: "Piyodalarning yer ostidan o'tish joyi" },
            { num: "5.17.2", img: "images/axborot-ishora/5.17.2.png", name: "Piyodalarning yer ostidan o'tish joyi" },
            { num: "5.17.3", img: "images/axborot-ishora/5.17.3.png", name: "Piyodalarning yer ustidan o'tish joyi" },
            { num: "5.17.4", img: "images/axborot-ishora/5.17.4.png", name: "Piyodalarning yer ustidan o'tish joyi" },
            { num: "5.18", img: "images/axborot-ishora/5.18.png", name: "Tavsiya etilgan tezlik" },
            { num: "5.19.1", img: "images/axborot-ishora/5.19.1.png", name: "Oxiri berk yo'l (ko'cha)" },
            { num: "5.19.2", img: "images/axborot-ishora/5.19.2.png", name: "Oxiri berk yo'l (ko'cha)" },
            { num: "5.19.3", img: "images/axborot-ishora/5.19.3.png", name: "Oxiri berk yo'l (ko'cha)" },
            { num: "5.20.1", img: "images/axborot-ishora/5.20.1a.png", name: "Yo'nalishlarning dastlabki ko'rsatkichi" },
            { num: "5.20.1", img: "images/axborot-ishora/5.20.1b.png", name: "Yo'nalishlarning dastlabki ko'rsatkichi" },
            { num: "5.20.1", img: "images/axborot-ishora/5.20.1c.png", name: "Yo'nalishlarning dastlabki ko'rsatkichi" },
            { num: "5.20.2", img: "images/axborot-ishora/5.20.2.png", name: "Yo'nalishlarning dastlabki ko'rsatkichi" },
            { num: "5.20.3", img: "images/axborot-ishora/5.20.3.png", name: "Harakatlanish tasviri" },
            { num: "5.21.1", img: "images/axborot-ishora/5.21.1.png", name: "Yo'nalish ko'rsatkichi" },
            { num: "5.21.2", img: "images/axborot-ishora/5.21.2.png", name: "Yo'nalishlar ko'rsatkichi" },
            { num: "5.22", img: "images/axborot-ishora/5.22.png", name: "Aholi yashaydigan joyning boshlanishi" },
            { num: "5.23", img: "images/axborot-ishora/5.23.png", name: "Aholi yashaydigan joyning oxiri" },
            { num: "5.24", img: "images/axborot-ishora/5.24.png", name: "Aholi yashaydigan joyning boshlanishi" },
            { num: "5.25", img: "images/axborot-ishora/5.25.png", name: "Aholi yashaydigan joyning oxiri" },
            { num: "5.26", img: "images/axborot-ishora/5.26.png", name: "Manzil nomi" },
            { num: "5.27", img: "images/axborot-ishora/5.27.png", name: "Masofalar ko'rsatkichi" },
            { num: "5.28", img: "images/axborot-ishora/5.28.png", name: "Kilometr belgisi" },
            { num: "5.29.1", img: "images/axborot-ishora/5.29.1.png", name: "Yo'l raqami" },
            { num: "5.29.2", img: "images/axborot-ishora/5.29.2a.png", name: "Yo'l raqami" },
            { num: "5.29.2", img: "images/axborot-ishora/5.29.2b.png", name: "Yo'l raqami" },
            { num: "5.29.2", img: "images/axborot-ishora/5.29.2c.png", name: "Yo'l raqami" },
            { num: "5.30.1", img: "images/axborot-ishora/5.30.1.png", name: "Yuk avtomobillari uchun harakatlanish yo'nalishi" },
            { num: "5.30.2", img: "images/axborot-ishora/5.30.2.png", name: "Yuk avtomobillari uchun harakatlanish yo'nalishi" },
            { num: "5.30.3", img: "images/axborot-ishora/5.30.3.png", name: "Yuk avtomobillari uchun harakatlanish yo'nalishi" },
            { num: "5.31", img: "images/axborot-ishora/5.31.png", name: "Aylanib o'tish tasviri" },
            { num: "5.32.1", img: "images/axborot-ishora/5.32.1.png", name: "Chetlab o'tish yo'nalishi" },
            { num: "5.32.2", img: "images/axborot-ishora/5.32.2.png", name: "Chetlab o'tish yo'nalishi" },
            { num: "5.32.3", img: "images/axborot-ishora/5.32.3.png", name: "Chetlab o'tish yo'nalishi" },
            { num: "5.33", img: "images/axborot-ishora/5.33.png", name: "To'xtash" },
            { num: "5.34.1", img: "images/axborot-ishora/5.34.1.png", name: "Boshqa qatnov qismiga qayta joylashish" },
            { num: "5.34.2", img: "images/axborot-ishora/5.34.2.png", name: "Boshqa qatnov qismiga qayta joylashish" },
            { num: "5.35", img: "images/axborot-ishora/5.35.png", name: "Reversiv harakatlanish" },
            { num: "5.36", img: "images/axborot-ishora/5.36.png", name: "Reversiv harakatlanish oxiri" },
            { num: "5.37", img: "images/axborot-ishora/5.37.png", name: "Reversiv harakatlanish yo'liga chiqish" },
            { num: "5.38", img: "images/axborot-ishora/5.38.png", name: "Turar-joy dahasi" },
            { num: "5.39", img: "images/axborot-ishora/5.39.png", name: "Turar-joy dahasining oxiri" },
            { num: "5.40", img: "images/axborot-ishora/5.40.png", name: "Falokatli holatlar uchun kirish yo'li" },
            { num: "5.41", img: "images/axborot-ishora/5.41.png", name: "Surat va video" },
            { num: "5.42", img: "images/axborot-ishora/5.42.png", name: "Qizil rangda o'ng tomonga burilish" },
            { num: "5.43", img: "images/axborot-ishora/5.43.png", name: "Radar" },
            { num: "5.44", img: "images/axborot-ishora/5.44.png", name: "Velosipedlar uchun harakatlanish bo'lagi" },
            { num: "5.45", img: "images/axborot-ishora/5.45.png", name: "Velosipedlar uchun harakatlanish bo'lagi oxiri" }
        ]
    },
    6: {
        title: "6. Servis belgilari",
        signs: [
            { num: "6.1",  img: "images/servis/6.1.png",  name: "Tibbiy yordam ko'rsatish joyi" },
            { num: "6.2",  img: "images/servis/6.2.png",  name: "Shifoxona" },
            { num: "6.3",  img: "images/servis/6.3.png",  name: "Yonilg'i shaxobchasi" },
            { num: "6.4",  img: "images/servis/6.4.png",  name: "Texnik xizmat ko'rsatish joyi" },
            { num: "6.5",  img: "images/servis/6.5.png",  name: "Transport vositalarini yuvish joyi" },
            { num: "6.6",  img: "images/servis/6.6.png",  name: "Telefon" },
            { num: "6.7",  img: "images/servis/6.7.png",  name: "Oshxona" },
            { num: "6.8",  img: "images/servis/6.8.png",  name: "Ichimlik suvi" },
            { num: "6.9",  img: "images/servis/6.9.png",  name: "Mehmonxona" },
            { num: "6.10", img: "images/servis/6.10.png", name: "Kemping" },
            { num: "6.11", img: "images/servis/6.11.png", name: "Dam olish joyi" },
            { num: "6.12", img: "images/servis/6.12.png", name: "Yo'l patrul xizmati maskani" },
            { num: "6.13", img: "images/servis/6.13.png", name: "Xalqaro avtomobil tashishlarini nazorat qilish punkti" },
            { num: "6.14", img: "images/servis/6.14.png", name: "Xojatxona" },
            { num: "6.15", img: "images/servis/6.15.png", name: "Axlat qutisi" },
            { num: "6.16", img: "images/servis/6.16.png", name: "Basseyn yoki sohil bo'yi" },
            { num: "6.17", img: "images/servis/6.17.png", name: "Polisiya" }
        ]
    },
    7: {
        title: "7. Transport vositalarining taniqlik belgilari",
        signs: [
            { num: "7.1",  img: "images/transport-taniqlik/7.1.png",  name: "Avtopoyezd" },
            { num: "7.2",  img: "images/transport-taniqlik/7.2.png",  name: "Turkumlangan shina o'rnatilgan transport vositasi" },
            { num: "7.3",  img: "images/transport-taniqlik/7.3.png",  name: "Boshqarishni o'rgatish transport vositasi" },
            { num: "7.4",  img: "images/transport-taniqlik/7.4.png",  name: "Kar-soqov yoki kar haydovchi boshqarayotgan avtomobil" },
            { num: "7.5",  img: "images/transport-taniqlik/7.5.png",  name: "Bolalar guruhi tashilayotgan transport vositasi" },
            { num: "7.6",  img: "images/transport-taniqlik/7.6.png",  name: "Nogiron haydovchi boshqarayotgan avtomobil" },
            { num: "7.7",  img: "images/transport-taniqlik/7.7.png",  name: "Shifokor haydovchi boshqarayotgan avtomobil" },
            { num: "7.8",  img: "images/transport-taniqlik/7.8.png",  name: "Xavfli yuk tashiyotgan avtomobil" },
            { num: "7.9",  img: "images/transport-taniqlik/7.9.png",  name: "Tezligi cheklangan" },
            { num: "7.10", img: "images/transport-taniqlik/7.10.png", name: "Katta o'lchamli yuk" },
            { num: "7.11", img: "images/transport-taniqlik/7.11.png", name: "Falokat sababli to'xtash" },
            { num: "7.12", img: "images/transport-taniqlik/7.12.png", name: "Uzun o'lchamli transport vositasi" }
        ]
    },
    8: {
        title: "8. Qo'shimcha axborot belgilari",
        signs: [
            { num: "7.1.1", img: "images/qoshimcha-axborot/7.1.1.png", name: "Manzilgacha bo'lgan masofa" },
            { num: "7.1.2", img: "images/qoshimcha-axborot/7.1.2.png", name: "Manzilgacha bo'lgan masofa" },
            { num: "7.1.3", img: "images/qoshimcha-axborot/7.1.3.png", name: "Manzilgacha bo'lgan masofa" },
            { num: "7.1.4", img: "images/qoshimcha-axborot/7.1.4.png", name: "Manzilgacha bo'lgan masofa" },
            { num: "7.2.1", img: "images/qoshimcha-axborot/7.2.1.png", name: "Ta'sir oralig'i" },
            { num: "7.2.2", img: "images/qoshimcha-axborot/7.2.2.png", name: "Ta'sir oralig'i" },
            { num: "7.2.3", img: "images/qoshimcha-axborot/7.2.3.png", name: "Ta'sir oralig'i" },
            { num: "7.2.4", img: "images/qoshimcha-axborot/7.2.4.png", name: "Ta'sir oralig'i" },
            { num: "7.2.5", img: "images/qoshimcha-axborot/7.2.5.png", name: "Ta'sir oralig'i" },
            { num: "7.2.6", img: "images/qoshimcha-axborot/7.2.6.png", name: "Ta'sir oralig'i" },
            { num: "7.3.1", img: "images/qoshimcha-axborot/7.3.1.png", name: "Ta'sir yo'nalishlari" },
            { num: "7.3.2", img: "images/qoshimcha-axborot/7.3.2.png", name: "Ta'sir yo'nalishlari" },
            { num: "7.3.3", img: "images/qoshimcha-axborot/7.3.3.png", name: "Ta'sir yo'nalishlari" },
            { num: "7.4.1", img: "images/qoshimcha-axborot/7.4.1.png", name: "Transport vositasining turi" },
            { num: "7.4.2", img: "images/qoshimcha-axborot/7.4.2.png", name: "Transport vositasining turi" },
            { num: "7.4.3", img: "images/qoshimcha-axborot/7.4.3.png", name: "Transport vositasining turi" },
            { num: "7.4.4", img: "images/qoshimcha-axborot/7.4.4.png", name: "Transport vositasining turi" },
            { num: "7.4.5", img: "images/qoshimcha-axborot/7.4.5.png", name: "Transport vositasining turi" },
            { num: "7.4.6", img: "images/qoshimcha-axborot/7.4.6.png", name: "Transport vositasining turi" },
            { num: "7.4.7", img: "images/qoshimcha-axborot/7.4.7.png", name: "Transport vositasining turi" },
            { num: "7.4.8", img: "images/qoshimcha-axborot/7.4.8.png", name: "Transport vositasining turi" },
            { num: "7.5.1", img: "images/qoshimcha-axborot/7.5.1.png", name: "Shanba, yakshanba va bayram kunlari" },
            { num: "7.5.2", img: "images/qoshimcha-axborot/7.5.2.png", name: "Ish kunlari" },
            { num: "7.5.3", img: "images/qoshimcha-axborot/7.5.3.png", name: "Hafta kunlari" },
            { num: "7.5.4", img: "images/qoshimcha-axborot/7.5.4.png", name: "Amal qilish vaqti" },
            { num: "7.5.5", img: "images/qoshimcha-axborot/7.5.5.png", name: "Amal qilish vaqti" },
            { num: "7.5.6", img: "images/qoshimcha-axborot/7.5.6.png", name: "Amal qilish vaqti" },
            { num: "7.5.7", img: "images/qoshimcha-axborot/7.5.7.png", name: "Amal qilish vaqti" },
            { num: "7.6.1", img: "images/qoshimcha-axborot/7.6.1.png", name: "Transport vositasini to'xtab turish joyiga qo'yish usuli" },
            { num: "7.6.2", img: "images/qoshimcha-axborot/7.6.2.png", name: "Transport vositasini to'xtab turish joyiga qo'yish usuli" },
            { num: "7.6.3", img: "images/qoshimcha-axborot/7.6.3.png", name: "Transport vositasini to'xtab turish joyiga qo'yish usuli" },
            { num: "7.6.4", img: "images/qoshimcha-axborot/7.6.4.png", name: "Transport vositasini to'xtab turish joyiga qo'yish usuli" },
            { num: "7.6.5", img: "images/qoshimcha-axborot/7.6.5.png", name: "Transport vositasini to'xtab turish joyiga qo'yish usuli" },
            { num: "7.6.6", img: "images/qoshimcha-axborot/7.6.6.png", name: "Transport vositasini to'xtab turish joyiga qo'yish usuli" },
            { num: "7.6.7", img: "images/qoshimcha-axborot/7.6.7.png", name: "Transport vositasini to'xtab turish joyiga qo'yish usuli" },
            { num: "7.6.8", img: "images/qoshimcha-axborot/7.6.8.png", name: "Transport vositasini to'xtab turish joyiga qo'yish usuli" },
            { num: "7.7", img: "images/qoshimcha-axborot/7.7.png", name: "Yurgizgichni ishlatmasdan to'xtab turish joyi" },
            { num: "7.8", img: "images/qoshimcha-axborot/7.8.png", name: "Pullik xizmat ko'rsatish joyi" },
            { num: "7.9", img: "images/qoshimcha-axborot/7.9.png", name: "To'xtab turish muddati cheklangan" },
            { num: "7.10", img: "images/qoshimcha-axborot/7.10.png", name: "Avtomobillarni ko'rikdan o'tkazish joyi" },
            { num: "7.11", img: "images/qoshimcha-axborot/7.11.png", name: "To'la vazni cheklangan" },
            { num: "7.12", img: "images/qoshimcha-axborot/7.12.png", name: "Xavfli yo'l yoqasi" },
            { num: "7.13", img: "images/qoshimcha-axborot/7.13.png", name: "Asosiy yo'lning yo'nalishi" },
            { num: "7.14", img: "images/qoshimcha-axborot/7.14.png", name: "Harakatlanish bo'lagi" },
            { num: "7.15", img: "images/qoshimcha-axborot/7.15.png", name: "Ko'zi ojiz piyodalar" },
            { num: "7.16", img: "images/qoshimcha-axborot/7.16.png", name: "Nam qoplama" },
            { num: "7.17", img: "images/qoshimcha-axborot/7.17.png", name: "Nogironlar" },
            { num: "7.18", img: "images/qoshimcha-axborot/7.18.png", name: "Nogironlar mustasno" },
            { num: "7.19", img: "images/qoshimcha-axborot/7.19.png", name: "Chorrahadagi kamera" },
            { num: "7.20", img: "images/qoshimcha-axborot/7.20.png", name: "Xavfli yuk" },
            { num: "7.21", img: "images/qoshimcha-axborot/7.21.png", name: "Evakuator ishlamoqda" },
            { num: "7.21.1", img: "images/qoshimcha-axborot/7.21.1.png", name: "Marshrutli transport vositasi turi" },
            { num: "7.21.2", img: "images/qoshimcha-axborot/7.21.2.png", name: "Marshrutli transport vositasi turi" },
            { num: "7.21.3", img: "images/qoshimcha-axborot/7.21.3.png", name: "Marshrutli transport vositasi turi" },
            { num: "", img: "images/qoshimcha-axborot/tosiq.png", name: "To'siq" }
        ]
    }
};
