const signsData = [
  { id: "1.1",   file: "1.1.png",     name: "Shlagbaumli temir yo'l kesishmasi" },
  { id: "1.2",   file: "1.2.png",     name: "Shlagbaumsiz temir yo'l kesishmasi" },
  { id: "1.3",   file: "1.3.png",     name: "Diqqat \"UZP\"" },
  { id: "1.3.1", file: "1.3.1.png",   name: "Bir izli temir yo'l" },
  { id: "1.3.2", file: "1.3.2.png",   name: "Ko'p izli temir yo'l" },
  { id: "1.4.1", file: "1.4.1.png",   name: "Temir yo'l kesishmasining oldingi belgisi" },
  { id: "1.4.2", file: "1.4.2.png",   name: "Temir yo'l kesishmasining oldingi belgisi" },
  { id: "1.4.3", file: "1.4.3.png",   name: "Temir yo'l kesishmasining oldingi belgisi" },
  { id: "1.4.4", file: "1.4.4.png",   name: "Temir yo'l kesishmasining oldingi belgisi" },
  { id: "1.4.5", file: "1.4.5.png",   name: "Temir yo'l kesishmasining oldingi belgisi" },
  { id: "1.4.6", file: "1.4.6.png",   name: "Temir yo'l kesishmasining oldingi belgisi" },
  { id: "1.5",   file: "1.5.png",     name: "Tramvay yo'li bilan keshuv" },
  { id: "1.6",   file: "1.6.png",     name: "Teng ahamiyatli yo'llar kesishuvi" },
  { id: "1.7",   file: "1.7.png",     name: "Aylanma harakatlanish bilan kesishuv" },
  { id: "1.8",   file: "1.8.png",     name: "Svetofor tartibga soladi" },
  { id: "1.9",   file: "1.9.png",     name: "Ko'tarma ko'prik" },
  { id: "1.10",  file: "1.10.png",    name: "Sohilga chiqish" },
  { id: "1.11.1",file: "1.11.1.png",  name: "Xavfli burilish" },
  { id: "1.11",  file: "1.11.png",    name: "Xavfli burilish" },
  { id: "1.12.1",file: "1.12.1.png",  name: "Xavfli burilishlar" },
  { id: "1.12.2",file: "1.12.2.png",  name: "Xavfli burilishlar" },
  { id: "1.13",  file: "1.13.png",    name: "Tik nishablik" },
  { id: "1.14",  file: "1.14.png",    name: "Tik balandlik" },
  { id: "1.15",  file: "1.15.png",    name: "Sirpanchiq yo'l" },
  { id: "1.16",  file: "1.16.png",    name: "Notekis yo'l" },
  { id: "1.17",  file: "1.17.png",    name: "Tosh otilish xavfi" },
  { id: "1.18.1",file: "1.18.1.png",  name: "Yo'lning torayishi" },
  { id: "1.18.2",file: "1.18.2.png",  name: "Yo'lning torayishi" },
  { id: "1.18.3",file: "1.18.3.png",  name: "Yo'lning torayishi" },
  { id: "1.19",  file: "1.19.png",    name: "Ikki tomonlama harakatlanish" },
  { id: "1.20",  file: "1.20.png",    name: "Piyodalar o'tish joyi" },
  { id: "1.21",  file: "1.21.png",    name: "Bolalar" },
  { id: "1.22",  file: "1.22.png",    name: "Velosiped yo'lkasi bilan kesishuv" },
  { id: "1.23",  file: "1.23.png",    name: "Ta'mirlash ishlari" },
  { id: "1.24",  file: "1.24.png",    name: "Mol haydab o'tish" },
  { id: "1.25",  file: "1.25.png",    name: "Yovvoyi hayvonlar" },
  { id: "1.26",  file: "1.26.png",    name: "Toshlar tushishi" },
  { id: "1.27",  file: "1.27.png",    name: "Yonlama shamol" },
  { id: "1.28",  file: "1.28.png",    name: "Pastlab uchuvchi samolyotlar" },
  { id: "1.29",  file: "1.29.png",    name: "Tonnel" },
  { id: "1.30",  file: "1.30.png",    name: "Boshqa xavf-xatar" },
  { id: "1.31",  file: "1.31.png",    name: "Sun'iy yo'l notekisliklari" },
  { id: "1.31.1",file: "1.31.1.png",  name: "Burilishning yo'nalishi" },
  { id: "1.31.2",file: "1.31.2.png",  name: "Burilishning yo'nalishi" },
  { id: "1.31.3",file: "1.31.3.png",  name: "Burilishning yo'nalishi" },
  { id: "1.32",  file: "1.32.png",    name: "Tirbandlik" },
];

export default signsData;
